feat: desktop tutorial in template's readme
JetBrains/compose-multiplatform-desktop-template pull request #2
Opened 2023-04-11 13:42 UTC by danil-pavlov

2023-04-11 16:37 UTC, igordmn reviewed
Thanks!

2023-04-11 16:37 UTC, igordmn commented on README.md
> +> We would appreciate your feedback in the public Slack channel [#compose-ios](https://kotlinlang.slack.com/archives/C0346LWVBJ4/p1678888063176359).
Here should be a link to #compose-desktop

2023-04-11 16:37 UTC, igordmn commented on README.md
> +* [Complete more Compose Multiplatform tutorials](https://github.com/JetBrains/compose-multiplatform#tutorials)
```suggestion
* [Complete more Compose Multiplatform tutorials](https://github.com/JetBrains/compose-multiplatform/tutorials/README.md)
```

2023-04-11 16:37 UTC, igordmn commented on README.md
> +* [Explore some more advanced Compose Multiplatform example projects](https://github.com/JetBrains/compose-multiplatform#examples)
```suggestion
* [Explore some more advanced Compose Multiplatform example projects](https://github.com/JetBrains/compose-multiplatform/examples/README.md)
```

2023-04-11 16:38 UTC, igordmn commented on README.md
> +> We would appreciate your feedback in the public Slack channel [#compose-ios](https://kotlinlang.slack.com/archives/C0346LWVBJ4/p1678888063176359).
```suggestion
> We would appreciate your feedback in the public Slack channel [#compose-desktop](https://kotlinlang.slack.com/archives/C01D6HTPATV).
```

2023-04-12 09:22 UTC, katia-energizer requested changes
LGTM. Just one comment.

2023-04-12 09:22 UTC, katia-energizer commented on README.md
> +> **Note**
We don't want feedback on the desktop target. We want for iOS and web only. Let's remove this note. 
Or rewrite:
> If you have any questions about Compose for Desktop, ask them in the [#compose-desktop](https://kotlinlang.slack.com/archives/C01D6HTPATV/p1678887144652589) Slack channel. ...

2023-04-12 09:22 UTC, katia-energizer commented on README.md
> +       kotlin("jvm") version "1.8.10"
```suggestion
       kotlin("jvm") version "1.8.20"
```

2023-04-12 10:40 UTC, igordmn commented on README.md
> +       id("org.jetbrains.compose") version "1.3.1"
```suggestion
       id("org.jetbrains.compose") version "1.4.0"
```

2023-04-12 10:41 UTC, igordmn commented on README.md
> +       id("org.jetbrains.compose") version "1.3.1"
```suggestion
       id("org.jetbrains.compose") version "1.4.0"
```

2023-04-12 10:41 UTC, igordmn commented on README.md
> +       kotlin("jvm") version "1.8.10"
```suggestion
       kotlin("jvm") version "1.8.20"
```

2023-04-12 14:33 UTC, merged